info.version: @project.version@
server:
  port: 20030
#注册中心
eureka:
  instance:
    health-check-url-path: /actuator/health
    home-page-url: /actuator/info
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@_version@
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/,http://admin:admin@peer3:8763/eureka/
#http基础认证
spring:
  application:
    name: eureka-swagger
  security:
    user:
      password: admin
      name: admin
  # admin
  boot:
    admin:
      client:
        auto-deregistration: true
        enabled: true
        instance:
          prefer-ip: true
          name: cloud-swagger-doc
  redis:
    host: localhost
    port: 6379
    password:

logging:
  config: classpath:logback.xml

# boot 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

#
#
##负载均衡
#ribbon:
#  Httpclient:
#    enable: false
#  OkHttp:
#    enable: true
#  MaxAutoRetries: 3 #同一个Server重试的次数(除去首次)
#  MaxAutoRetriesNextServer: 0 #切换相同Server的次数
#  ReadTimeout: 30000
#  ConnectTimeout: 30000
#  eager-load:
#        enabled: true
#
#feign:
#  hystrix:
#    enabled: true
#  okhttp:
#    enable: true
#  httpclient:
#    enable: false
#  client:
#    config:
#      feignName:
#        connectTimeout: 30000
#        readTimeout: 30000
#
#hystrix:
#  command:
#    default:
#      execution:
#         isolation:
#           thread:
#             timeoutInMilliseconds: 30000
#   threadpool:
#     default:
#       coreSize: 500 #缺省为10