server:
  port: 5002

zipkin:
  collector:
    rabbitmq:
      addresses: 127.0.0.1:5682
      password: root
      username: root
      queue: zipkin
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 127.0.0.1:9200
      cluster: elasticsearch
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1

logging:
  config: classpath:logback.xml

# boot 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"