
sharding:
      jdbc:
        datasource:
          names: ds-master,ds-slave-0
          ds-master:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://172.16.220.126:3306/hmd_dw?autoReconnect=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
            username: dev
            password: hmd)P:?942
          ds-slave-0:
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://172.16.220.126:3306/hmd_dw?autoReconnect=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
            username: dev
            password: hmd)P:?942
        config:
          masterslave:
            load-balance-algorithm-type: round_robin
            name: ds_ms
            master-data-source-name: ds-master
            slave-data-source-names: ds-slave-0
          sharding:
            props:
               sql-show: false
               executor-size: 10

mybatis-plus:
    mapper-locations: classpath*:mapper/*Mapper.xml
    typeAliasesPackage: com.homedo.report.domain.*.entity
    configuration:
      map-underscore-to-camel-case: true  #使用驼峰法映射属性
      defaultStatementTimeout: 25000
      defaultExecutorType: REUSE
      lazyLoadingEnabled: true
      multipleResultSetsEnabled: true
      useColumnLabel: true
      cacheEnabled: false
    global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      db-column-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      #capital-mode: true
      #序列接口实现类配置
      #key-generator: com.baomidou.springboot.xxx
      #逻辑删除配置
      #logic-delete-value: 0
      #logic-not-delete-value: 1
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
      #自定义SQL注入器
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
logging:
  config: classpath:logback.xml

