info.version: @project.version@
server:
  port: 8080
spring:
  security:
    user:
      password: admin
      name: admin
  application:
    name: cloud-eureka
  boot:
    swgger:
      config:
        version: 1.0.0
    admin:
      client:
        auto-deregistration: true
        enabled: true
        instance:
          prefer-ip: true
          name: cloud-eureka
eureka:
  server:
    batch-replication: true
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    health-check-url-path: /actuator/health
    home-page-url: /actuator/info
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@_version@
logging:
  config: classpath:logback.xml

# boot 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
