spring:
  application:
    name: apollo-portal
  profiles:
    active: github
  resources:
    cache-period: 3600

server:
  port: 10000
  
#logging:
#  path: /opt/logs/100003173
#  file: ${logging.path}/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


