
spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
              locator:
                enabled: true
      routes:
      - id: cloud-admin
        uri: http://127.0.0.1
        order: 10000
        predicates:
        - Query=cloud-admin

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

management.endpoints.web.exposure.include: '*'
