spring:
  application:
    name: apollo-configservice
  profiles:
    active: github

ctrip:
  appid: 100003171
  
server:
  port: 9090

#  path: /opt/logs/100003171
#  file: ${logging.path}/apollo-configservice.log
logging:
  config: classpath:logback.xml
