info.version: @project.version@

server:
  port: 20000
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
# 注册服务
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/,http://admin:admin@peer2:8762/eureka/,http://admin:admin@peer3:8763/eureka/

spring:
  application:
    name: cloud-admin
  profiles:
    active:
    - secure

  #  boot:
  #    admin:
  #      turbine:
  #        location: cloud-admin
  #        enabled: true
  #      routes:
  #        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
  boot:
    admin:
      ui:
        title: 服务治理监控平台
      probed-endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti


# boot 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" ## 用于服务下线可以调用/service-registry端点 //当服务流量没了再停止服务

logging:
  config: classpath:logback.xml
---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "admin"
      password: "admin"
eureka:
  instance:
    metadata-map:
      user.name: "admin"         #These two are needed so that the server
      user.password: "admin" #can access the protected client endpoints