info.version: @project.version@
server:
  port: 20000
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads
# 注册服务
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8080/eureka/

spring:
  application:
    name: cloud-admin
  security:
    user:
      password: admin
      name: admin
  boot:
    admin:
      turbine:
        location: cloud-admin
        enabled: true
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
#  boot:
#    admin:
#      ui:
#        title: 服务治理监控平台
#      probed-endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
management:
  endpoint:
    health:
      show-details: always
