spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github

ctrip:
  appid: 100003172
  
server:
  port: 8090

#  path: /opt/logs/100003172
#  file: ${logging.path}/apollo-adminservice.log
logging:
  config: classpath:logback.xml
